# Generated by Django 3.2 on 2023-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
